services:
  - type: web
    name: loan-app-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://loanapp-8s0y5vrn2-asadalibhattis-projects.vercel.app
      - key: USE_S3
        value: false 